#! /bin/sh


BGreen="\e[1;32m"
BYellow="\e[1;33m"
reset="\e[0m"

path="$(dirname $(readlink -e ${0}))"
slice="/assets/building"

root="${path%%${slice}}"


function backup() {

    if [[ -d "/etc" ]]
    then
        sudo mv "/etc" "/etc.backup"
    fi

}

function configuration() {

    local root="${root}/dotdrops"

    sudo cp -r "${root}/etc" "/etc"

}

function main() {

    backup
    echo -e "[${BGreen}*${reset}] Modified files have been backed up."
    configuration
    echo -e "[${BGreen}*${reset}] Dotdrops copied to root directory"

}


main